project:
  type: book

book:
  title: "pkpd notes"
  author: "Nazmul Alam"
  date: "2023-02-06"
  chapters:
    - index.qmd
    - NCAintroduction.qmd
    - WinNonlinIntro.qmd
    - WinNonlinModel.qmd
    - TechNotes.qmd
    - Rnotes.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

