# My Notes

## Courses

1.  (103-OD) Fundamentals of Pharmacokinetics \[Conceptual Course\]

2.  (105-OD) Noncompartmental Data Analysis \[Conceptual Course\]

3.  (122-OD) Introduction to Phoenix WinNonlin (Part 1) - NCA

4.  (123-OD) Introduction to Phoenix WinNonlin (Part 2) - Modeling

### create a new repository on the command line

    echo "# test" >> README.md
    git init
    git add README.md
    git commit -m "first commit"
    git branch -M main
    git remote add origin https://github.com/drnazmul/test.git
    git push -u origin main

### ...or push an existing repository from the command line

    git remote add origin https://github.com/drnazmul/test.git
    git branch -M main
    git push -u origin main

After any change made on github repo but not on the local folder, do the following

    git pull --rebase origin main
    git push origin main

### Publishing Quarto site or book

Publish from Git Provider

https://quarto.org/docs/publishing/netlify.html#publish-from-git-provider

### Custom domain on Netlify with Namecheap

-   Go to Namecheap's account, click Manage on the active domain

-   on "Name Server" select "Custom DNS" option

-   Go to "Domain Settings" of Netlify

-   Custom Domain : Options: Edit site name

-   Click on "Add custom domain" and add your domain

-   Under "primary domain" options, click "Setup Netlify DNS"

-   Click verify tab

-   Click Add domain tab

-   Click Continue

-   copy all the four name servers and paste to the DNS server on Namecheap

-   Click Done on Netlify

-   

## PBPK notes

https://www.admescope.com/whats-new/blog/2016/pbpk-what-it-is-for

https://www.fda.gov/regulatory-information/search-fda-guidance-documents

https://www.boomer.org/

https://www.pkpd168.com/

https://bebac.at/

Data: Collection of observations or facts. Can be text, number, audio, video, pics,

-   We encounter data 1. purposefully 2. Unintentionally

-   Understanding the data we encounter everyday is where the data literacy comes in.

-   Data Literacy: how a person interacts with data to make sense or the world around them

-   Data literate person:

    -   recognize usefulness of the data

    -   Interrogate reliability: When, where and how the data was collected?

    -   Discover meaning

    -   Make decision

    -   Communicate findings

    -   Do everything ethically

    ### Recognize usefulness of the data

    when you encounter a data: ask: Is this data relevant and useful to me? If so, how?

    \% increase = (final value - initial value)/initial value \* 100

    Questions to ask:

-   what's the story the author is trying to make

-   What data are they presenting and how are the presenting it?

-   What is the agenda behind the information being presented

-   how might this data help others to make decision

-   what do you like and what would you do differently?

Data: which is most useful? Which is not relavant?

Make a plan with the questions

Scaptacle eays and curious mind are essential for data literate person

## Courses to take

-   https://www.coursera.org/specializations/precalculus-data-modelling

-   NONMEM paper @keizer2013

-   PM and ML paper @keutzer2022

## latex in rmarkdown

https://rpruim.github.io/s341/S19/from-class/MathinRmd.html
